### ISSUE TITLE
cargo-apk: Cannot find `$ANDROID_HOME/tools/ant/build.xml`

### ISSUE THREAD

**Issue by yoanlcq** [tomaka/android-rs-glue#140]
Greetings, 

I'm stuck at the following error reported by `cargo-apk`.  
For context, the crate is `/home/yoon/android-foo`, freshly created from `cargo new --bin`, and my Android SDK is located in `/usr/local/android-sdk` (I wanted to keep the log message as-is).
```
  Cargo-Apk: Compiling android_native_app_glue.c
  Cargo-Apk: Compiling injected-glue
  Cargo-Apk: Compiling injected-glue
  Cargo-Apk: Compiling glue_obj
  Cargo-Apk: Compiling crate
   Compiling android-foo v0.1.0 (file:///home/yoon/android-foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.34 secs
  Cargo-Apk: Invoking ant
Error executing ["ant", "debug"]
Status code 1
Stdout
--------------------
Buildfile: /home/yoon/android-foo/target/android-artifacts/build/build.xml
Stderr
--------------------

BUILD FAILED
/home/yoon/android-foo/target/android-artifacts/build/build.xml:6: Cannot find /usr/local/android-sdk/tools/ant/build.xml imported from /home/yoon/android-foo/target/android-artifacts/build/build.xml
```
Content of `/home/yoon/android-foo/target/android-artifacts/build/build.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="android-foo" default="help">
    <property file="local.properties" />
    <loadproperties srcFile="project.properties" />
    <import file="custom_rules.xml" optional="true" />
    <import file="${sdk.dir}/tools/ant/build.xml" />

</project>
```

There's no `ant` directory under `tools` in my Android SDK. I've searched for it elsewhere, and looking at the SDK manager and other settings, there's nothing related I could install.  
At the risk of stating the obvious, I made sure to follow the instructions on the README.

I'm on Ubuntu, Android Studio 2.1.2, SDK tools 26.0.2, and Cargo 0.21.0-nightly.

**Comment by tomaka** [comment]
This is probably caused by some changes in the SDK.
I'm not really up-to-date unfortunately, but I heard stuff about removing support for ant or something :-/

**Comment by yoanlcq** [comment]
Thanks for the info ! It led me to this [StackOverflow answer](https://stackoverflow.com/a/42921645), and from there it seems I could fiddle something (or at least know what to search for). I'll let you know if I get this to work.

**Comment by tomaka** [comment]
Should be fixed by #144

**Comment by yoanlcq** [comment]
Sorry for coming back so late, but I still have the exact same problem even after uninstalling and re-installing `cargo-apk` - it's still trying to invoke `ant debug` and I get the same error message.  

Is there anything I'm missing ? Thanks a lot in advance.

**Comment by tomaka** [comment]
Err, I accidentally removed the script that auto-publishes new versions of cargo-apk. Should be good now.

**Comment by yoanlcq** [comment]
Alright, I was able to make the basic example work and see messages through logcat. Thanks @tomaka !
